name: Release Workflow

on:
  pull_request:
      types: [opened, reopened]

jobs:
  build:
    name: Build node
    uses: ./.github/workflows/build.yml
    with:
      runs-on: "ubuntu-latest"
  terraform-plan:
    name: Terraform plan
    needs: [build]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      config_directory: "/terraform"
    secrets: inherit
  terraform-apply:
    name: Terraform apply
    needs: [terraform-plan]
    uses: ./.github/workflows/terraform-apply.yml 
