name: "Terraform Apply"

on: 
  workflow_call:
    inputs:
      terraform-version:
        default: 1.5.0
        type: string
        

jobs:
  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{inputs.terraform-version}}

      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.event.number }}
          path: ${{ inputs.project-folder }}

      - name: Zip Files
        run: zip -qq -r ./terraform/dist.zip dist  
         
      - name: Terraform apply
        if: github.event.pull_request.merged == true && success()
        continue-on-error: true
        run: |
          terraform apply -input=false -auto-approve -no-color



